Django/test1/compras/urls.py
from django.conf.urls import url
from .views import NuevaEntrada,ListarEntrada,EditarEntrada,EliminarEntrada
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^nueva_entrada/',login_required(NuevaEntrada.as_view()),name="nueva_entrada"),
    url(r'^listar_entrada/',login_required(ListarEntrada.as_view()),name="listar_entrada"),
    url(r'^editar_entrada/(?P<pk>\d+)/$',login_required(EditarEntrada.as_view()),name="editar_entrada"),
    url(r'^eliminar_entrada/(?P<pk>\d+)/$',login_required(EliminarEntrada.as_view()),name="eliminar_entrada"),
]

Django/test1/sala/urls.py
from django.conf.urls import url
from .views import CrearPelicula,ListarPelicula,EditarPelicula,EliminarPelicula,CrearSala,EditarSala,ListarSala,EliminarSala

urlpatterns = [
######PELICULA##############
    url(r'^crear_pelicula/',CrearPelicula.as_view(),name = "crear_pelicula"),
    url(r'^listar_pelicula/',ListarPelicula.as_view(),name = "listar_pelicula"),
    url(r'^editar_pelicula/(?P<pk>\d+)/',EditarPelicula.as_view(),name = "editar_pelicula"),
    url(r'^eliminar_pelicula/(?P<pk>\d+)/',EliminarPelicula.as_view(),name = "eliminar_pelicula"),

##########SALA##############
    url(r'^crear_sala',CrearSala.as_view(),name = "crear_sala"),
    url(r'^listar_sala',ListarSala.as_view(),name = "listar_sala"),
    url(r'^editar_sala/(?P<pk>\d+)/$',EditarSala.as_view(),name = "editar_sala"),
    url(r'^eliminar_sala/(?P<pk>\d+)/$',EliminarSala.as_view(),name = "eliminar_sala"),
]

Django/test1/test1/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import login,logout_then_login
from usuarios.views import index
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',login_required(index), name='index'),
    url(r'^usuarios/',include('usuarios.urls',namespace = "usuarios")),
    url(r'^sala/',include('sala.urls',namespace = "sala")),
    url(r'^compras/',include('compras.urls',namespace = "compras")),
    url(r'^accounts/login', login,{'template_name':'usuarios/login.html'},name='login'),
    url(r'^logout/',logout_then_login,name='logout'),
]

Django/test1/usuarios/urls.py
from django.conf.urls import url
from .views import NuevoUsuario,userlogin
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^nuevo_usuario/',login_required(userlogin),name = "nuevo_usuario"),
]

Django/test1/test1/templates/test1/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Crud Basico</title>
  <nav >
    <div >
      <div >
        <a href="#">WebSiteName</a>
      </div>
      <ul >
        {% if user.is_authenticated %}
          <li><a href="{% url 'index' %}">Home</a></li>
          <li>{{ user.username }}</li>
          {% if user.is_gerente or user.is_colaborador %}
            <li><a href="{% url 'compras:listar_entrada' %}">Compras</a></li>
          {% endif %}
          {% if user.is_gerente %}
            <li><a href="{% url 'sala:listar_pelicula' %}">Sala</a></li>
          {% endif %}
          {% if user.is_superuser %}
            <li><a href="{% url 'usuarios:nuevo_usuario' %}">Usuarios</a></li>
          {% endif %}
        {% endif %}
      </ul>
    </div
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>