Django/veterinaria/atencion/urls.py
from django.conf.urls import url
from views import PersonaList,PersonaCreate,PersonaDelete,PersonaUpdate,VeterinarioList,VeterinarioCreate,VeterinarioDelete,VeterinarioUpdate

urlpatterns = [    
    url(r'^listar$',PersonaList.as_view(),name='persona_list'),
    url(r'^crear$',PersonaCreate.as_view(),name='persona_create'),
    url(r'^eliminar/(?P<pk>\d+)$',PersonaDelete.as_view(),name='persona_delete'),
    url(r'^editar/(?P<pk>\d+)$',PersonaUpdate.as_view(),name='persona_editar'),
    url(r'^listar/veterinario$',VeterinarioList.as_view(),name='veterinario_list'),
    url(r'^crear/veterinario$',VeterinarioCreate.as_view(),name='veterinario_create'),
    url(r'^eliminar/veterinario/(?P<pk>\d+)$',VeterinarioDelete.as_view(),name='veterinario_delete'),
    url(r'^editar/veterinario/(?P<pk>\d+)$',VeterinarioUpdate.as_view(),name='veterinario_editar'),
]

Django/veterinaria/mascota/urls.py
from django.conf.urls import url
from mascota.views import MascotaList,MascotaCreate,MascotaUpdate,MascotaDelete

urlpatterns = [    
    url(r'^listar$',MascotaList.as_view(),name='home_mascota'),
    url(r'^nuevo$',MascotaCreate.as_view(),name='crear_mascota'),
    url(r'^editar/(?P<pk>\d+)/$',MascotaUpdate.as_view(),name='editar_mascota'),
    url(r'^eliminar/(?P<pk>\d+)/$',MascotaDelete.as_view(),name='eliminar_mascota'),
]

Django/veterinaria/veterinaria/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import login,logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/',include('mascota.urls',namespace='mascota')),
    url(r'^usuario/',include('usuario.urls',namespace='usuario')),
    url(r'^accounts/login', login,{'template_name':'usuario/login.html'},name='login'),
    url(r'^logout/',logout_then_login,name='logout'),
    url(r'^atencion/',include('atencion.urls',namespace='atencion')),
]

Django/veterinaria/veterinaria/templates/veterinaria/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<title>{% block title %}Bienvenidos a Veterinaria S.A{% endblock %}</title>
</head>
	<body>
	<div>		
		<nav>
			{% if user.is_authenticated %}
				|
				<a href="{% url 'mascota:home_mascota' %}">Home</a>
				|
				<a href="{% url 'atencion:persona_create' %}">Nueva Persona</a>
				|
				<a href="{% url 'atencion:persona_list' %}">Listado de Personas</a>
				|
				<a href="{% url 'mascota:crear_mascota' %}">Nueva mascota</a>
				|
				{% if user.is_superuser %}
					<a href="{% url 'atencion:veterinario_create' %}">Nueva Vacuna</a>
					|
					<a href="{% url 'atencion:veterinario_create' %}">Nuevo Veterinario</a>
					|
					<a href="{% url 'atencion:veterinario_list' %}">Listado de Veterinarios</a>
					|
					<a href="{% url 'atencion:veterinario_list' %}">Listado de Vacunas</a>
					|
				{% endif %}
				|
				<a href="{% url 'logout' %}">Salir</a>	
				|
			{% else %}
				<a href="{% url 'login' %}">Entrar</a>
				|
			{% endif %}
		</nav>
		
	</div>

	<section>
		{% block section %}
		{% endblock %}
	</section>
	<script src="{% static 'js/bootstrap.min.js' %}" ></script>
	
</body>
</html>